/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoazar;

import java.awt.Dimension;
import java.awt.Toolkit;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author alumno
 */
public class Ruleta extends javax.swing.JFrame {

    /**
     * Creates new form Ruleta
     */
    public Ruleta() {
        initComponents();         
        txtMontoFinal.setText(String.valueOf(saldoInicial));        
         // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        this.setLocation(x, y);
        showMessageDialog(null, "Instrucciones: \n 1. Elige un numero \n 2. Elige el monto a apostar"
                + "\n Reglas: \n"
                + "1.Si obtienes el mismo numero ganas el triple de lo apostado \n"
                + "2.Si le atinas a que es par o impar ganas el doble");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msjFinal = new javax.swing.JLabel();
        inpMonto = new javax.swing.JTextField();
        inpNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMontoFinal = new javax.swing.JLabel();
        btnApostar = new javax.swing.JButton();
        txtMsj = new javax.swing.JLabel();
        msjMontoFinal = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("AcadEref", 0, 12)); // NOI18N

        msjFinal.setFont(new java.awt.Font("Segoe Marker", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel1.setText("Elige un numero");

        jLabel4.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel4.setText("Apuesta");

        jLabel3.setFont(new java.awt.Font("Segoe Marker", 0, 48)); // NOI18N
        jLabel3.setText("Juego");

        jLabel5.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel5.setText("Dinero");

        txtMontoFinal.setFont(new java.awt.Font("Segoe Marker", 0, 36)); // NOI18N
        txtMontoFinal.setText("0");

        btnApostar.setFont(new java.awt.Font("Segoe Marker", 1, 18)); // NOI18N
        btnApostar.setText("Apostar");
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        txtMsj.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N

        msjMontoFinal.setFont(new java.awt.Font("Segoe Marker", 0, 36)); // NOI18N

        btnTerminar.setFont(new java.awt.Font("Segoe Marker", 1, 18)); // NOI18N
        btnTerminar.setText("Recoger Recompensa");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegoazar/img/ruleta.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(inpNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(371, 371, 371)
                                .addComponent(msjMontoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMsj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(msjFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(185, 185, 185)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMontoFinal))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inpMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(txtMsj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msjFinal)
                        .addGap(106, 106, 106)))
                .addComponent(msjMontoFinal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private float saldoInicial = 100;
    
    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
       
        String numero = inpNumero.getText();
        String monto = inpMonto.getText();                                                
        
        int inumero=0;
        float fmonto =0;
        try {
            inumero = Integer.parseInt(numero);
            fmonto = Float.parseFloat(monto);
        } catch (Exception e) {
            showMessageDialog(null, "Upps! ingrese un valor valido");
            return;
        }
        
        Calculo c = new Calculo();        
        if(!c.valido(inumero, fmonto, saldoInicial)){            
            showMessageDialog(null, c.msjError);
            return;
        }
                
        saldoInicial = saldoInicial-fmonto;
        int aleatorio = (int) (Math.random() * 9) + 1;
        
        //Dice al usuario que numero cayo        
        showMessageDialog(null, "Cayo "+String.valueOf(aleatorio)+"!");
        
        boolean gano = false;
        String msjGano = "";
        //Valida que el numero coninsida en ser par o impar
        if(c.esIgual(inumero,aleatorio)){
            fmonto=c.porTres(fmonto);
            gano = true;
             msjGano = "Felicidades Ganaste Triple!";
        }else{
            if(c.esPar(inumero) && c.esPar(aleatorio)){
                fmonto=c.porDos(fmonto);
                gano = true;
                msjGano = "Felicidades Ganaste Doble!";
            }else{
                if(!c.esPar(inumero) && !c.esPar(aleatorio)){
                    fmonto=c.porDos(fmonto);
                    gano = true;
                    msjGano = "Felicidades Ganaste Doble!";
                }   
            }   
        }
        
        if(gano){            
            msjMontoFinal.setText(String.valueOf(fmonto));
            saldoInicial = saldoInicial+fmonto;
            txtMontoFinal.setText(String.valueOf(saldoInicial));
            showMessageDialog(null, msjGano);
        }else{            
            msjMontoFinal.setText("");            
            txtMontoFinal.setText(String.valueOf(saldoInicial));
            showMessageDialog(null, "Intentalo de nuevo, tendras suerte a la proxima");            
        }      
        inpMonto.setText("");
        inpNumero.setText("");
    }//GEN-LAST:event_btnApostarActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        showMessageDialog(null, "Te llevaste "+String.valueOf(saldoInicial));
        inpMonto.setText("");
        inpNumero.setText("");
        saldoInicial = 100;
        txtMontoFinal.setText(String.valueOf(saldoInicial));
        showMessageDialog(null, "Ok, juega de nuevo");
    }//GEN-LAST:event_btnTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JTextField inpMonto;
    private javax.swing.JTextField inpNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel msjFinal;
    private javax.swing.JLabel msjMontoFinal;
    private javax.swing.JLabel txtMontoFinal;
    private javax.swing.JLabel txtMsj;
    // End of variables declaration//GEN-END:variables
}
